# Exercise the patch on freshly generated entry points and on a second run.
set(GENERATED_DIR "${BINARY_DIR}/generated-parser-patch")
file(MAKE_DIRECTORY "${GENERATED_DIR}")
configure_file("${SOURCE_DIR}/cmake/PatchGenerated.cmake.in"
    "${GENERATED_DIR}/PatchGenerated.cmake" @ONLY)
file(WRITE "${GENERATED_DIR}/Parser.H"
    "Query* pQuery(FILE *inp);\nQuery* pQuery(const char *str);\n")
file(WRITE "${GENERATED_DIR}/grammar.y"
    "extern void grammar_lex_destroy();\nQuery* pQuery(const char *str);\n")
file(WRITE "${GENERATED_DIR}/Parser.C" "extern void grammar_lex_destroy();\n")
file(WRITE "${GENERATED_DIR}/grammar.l" "%option noyywrap\n")
file(WRITE "${GENERATED_DIR}/Lexer.C" "#include <stdio.h>\n")

function(run_patch)
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${GENERATED_DIR}/PatchGenerated.cmake"
        RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Generated parser patch failed")
    endif()
endfunction()
run_patch()
file(READ "${GENERATED_DIR}/Parser.H" header)
foreach(declaration "Query* pQuery(FILE *inp);" "Query* psQuery(const char *str);")
    string(FIND "${header}" "${declaration}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Parser.H lost entry point: ${declaration}")
    endif()
endforeach()
file(READ "${GENERATED_DIR}/grammar.y" grammar)
string(FIND "${grammar}" "Query* psQuery(const char *str);" found)
if(found EQUAL -1)
    message(FATAL_ERROR "String entry point must be corrected before Bison runs")
endif()

set(files Parser.H grammar.y Parser.C grammar.l Lexer.C)
foreach(name IN LISTS files)
    file(SHA256 "${GENERATED_DIR}/${name}" "hash_${name}")
    file(TIMESTAMP "${GENERATED_DIR}/${name}" "time_${name}" UTC)
endforeach()
# Ensure a rewrite would have a different timestamp even on coarse filesystems.
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1.1)
run_patch()
foreach(name IN LISTS files)
    file(SHA256 "${GENERATED_DIR}/${name}" hash)
    file(TIMESTAMP "${GENERATED_DIR}/${name}" time UTC)
    if(NOT hash STREQUAL "${hash_${name}}" OR NOT time STREQUAL "${time_${name}}")
        message(FATAL_ERROR "Repeated patch rewrote ${name}")
    endif()
endforeach()
